renamed "sensor_data" table to "migrations"
lorawan-team/delta_service pull request #1
Opened 2016-09-19 12:09 UTC by LeanderM

2016-09-19 13:28 UTC, LeanderM commented
do not merge yet; last minute error

2016-09-20 07:40 UTC, JesseLabruyere commented on databases/migrations/2016_09_12_113249_create_migrations_table.php
> +		Schema::create('migrations', function(Blueprint $table)
Dit moet 'measurement' zijn niet migrations.

2016-09-20 07:41 UTC, JesseLabruyere commented on src/Measurements/MeasurementModel.php
> +    protected $table = 'measurements';
Tabel namen enkelvoud 'measurement'

2016-09-20 07:43 UTC, JesseLabruyere requested changes
Zou je hem niet eerst op development mergen?

2016-09-21 10:01 UTC, LeanderM commented
Er is nog geen development branch op deze module, master was de enige optie.

2016-09-21 10:04 UTC, LeanderM commented on src/Measurements/MeasurementModel.php
> +    protected $table = 'measurements';
opgelost

2016-09-21 10:05 UTC, LeanderM commented on databases/migrations/2016_09_12_113249_create_migrations_table.php
> +		Schema::create('migrations', function(Blueprint $table)
weet ik, dit was lokaal al opgelost. bug had een andere oorzaak

2016-09-22 13:10 UTC, closed without merging